Stat svc
Cra5h23/java-explore-with-me pull request #1
Opened 2024-06-16 09:54 UTC by Cra5h23

Первая часть диплома

2024-06-19 07:09 UTC, db-exp requested changes

2024-06-19 07:09 UTC, db-exp commented on ewm-stats-service/stats-service/src/main/java/ru/practicum/controller/StatsController.java
> +    public ResponseEntity<?> getStats(@RequestParam String start,
Валидацию на start/end добавить не хочешь?

2024-06-19 07:09 UTC, db-exp commented on ewm-stats-service/stats-service/src/main/resources/schema.sql
не хватает размерности на varchar - для ip, например, 255 явно перебор

2024-06-20 07:29 UTC, db-exp approved these changes

2024-06-20 07:29 UTC, db-exp commented on ewm-stats-service/stats-service/src/main/resources/schema.sql
> +app VARCHAR NOT NULL,
в следующем спринте пропиши, пожалуйста, явно размер

2024-06-20 10:16 UTC, Cra5h23 commented
Закончил первую часть

2024-06-20 10:16 UTC, merged