Main svc
Cra5h23/java-explore-with-me pull request #2
Opened 2024-07-02 14:22 UTC by Cra5h23

2024-07-04 17:32 UTC, Cra5h23 commented
Отправляю на ревью

2024-07-05 11:48 UTC, db-exp requested changes

2024-07-05 11:48 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/category/controller/AdminCategoryController.java
> +    public ResponseEntity<Object> deleteCategory(@PathVariable Long catId) {
к целочисленным параметрам там, где они не могут быть null можно добавить во всех местах positive/notnull

2024-07-05 11:48 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/compilation/service/impl/CompilationServiceImpl.java
> +public class CompilationServiceImpl implements CompilationService {
потерял Transactional (можно добавлять - если что там Propagation по дефолту - Required и оно либо берет существующую, либо создает новую если ее нет)

2024-07-05 11:48 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/event/service/impl/EventServiceImpl.java
> +    public Event checkEvent(Long eventId) {
тут readOnly=true

2024-07-05 11:48 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/event/service/impl/EventServiceImpl.java
> +    public Event checkEvent(Long eventId, Long initiatorId) {
тут readOnly=true

2024-07-05 11:48 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/event/service/impl/EventServiceImpl.java
> +    public Map<Long, Long> getViews(LocalDateTime rangeStart, LocalDateTime rangeEnd, List<String> uris) {
тут readOnly=true

2024-07-05 11:48 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/event/model/Event.java
> +    public boolean equals(Object o) {
а чего не аннотация Data и минус Getter/Setter итп

2024-07-05 11:48 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/participation/service/impl/ParticipationRequestServiceImpl.java
> +    public ParticipationRequest checkParticipationRequest(Long partId) {
тут readOnly=true

2024-07-05 11:48 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/participation/service/impl/ParticipationRequestServiceImpl.java
> +    public ParticipationRequest checkParticipationRequest(Long partId, Long userId) {
тут readOnly=true

2024-07-05 11:48 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/participation/service/impl/ParticipationRequestServiceImpl.java
> +    public List<ParticipationRequestDto> getEventRequests(Long userId, Long eventId) {
тут readOnly=true

2024-07-05 11:48 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/participation/service/impl/PrivateParticipationRequestServiceImpl.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
а почему Requires_new?

2024-07-05 11:48 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/participation/service/impl/PrivateParticipationRequestServiceImpl.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
кажется тут вообще ничего больше не нужно даже Transactional - метод вспомогательный и приватный

2024-07-07 12:51 UTC, db-exp requested changes

2024-07-07 12:51 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/compilation/service/impl/CompilationServiceImpl.java
> +    @Override
тут транзакция только на чтение и выше тоже

2024-07-08 08:03 UTC, db-exp approved these changes

2024-07-08 11:54 UTC, merged